// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fuota/fuota.proto

package fuota

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MulticastGroupType int32

const (
	// Class-B.
	MulticastGroupType_CLASS_B MulticastGroupType = 0
	// Class-C.
	MulticastGroupType_CLASS_C MulticastGroupType = 1
)

var MulticastGroupType_name = map[int32]string{
	0: "CLASS_B",
	1: "CLASS_C",
}

var MulticastGroupType_value = map[string]int32{
	"CLASS_B": 0,
	"CLASS_C": 1,
}

func (x MulticastGroupType) String() string {
	return proto.EnumName(MulticastGroupType_name, int32(x))
}

func (MulticastGroupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{0}
}

type Deployment struct {
	// Application ID.
	ApplicationId int64 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Devices to include in this deployment.
	DevEuis [][]byte `protobuf:"bytes,2,rep,name=dev_euis,json=devEuis,proto3" json:"dev_euis,omitempty"`
	// Multicast-group type.
	MulticastGroupType MulticastGroupType `protobuf:"varint,3,opt,name=multicast_group_type,json=multicastGroupType,proto3,enum=fuota.MulticastGroupType" json:"multicast_group_type,omitempty"`
	// Multicast data-rate.
	MulticastDr uint32 `protobuf:"varint,4,opt,name=multicast_dr,json=multicastDr,proto3" json:"multicast_dr,omitempty"`
	// Multicast ping-slot period (Class-B only).
	MulticastPingSlotPeriod uint32 `protobuf:"varint,5,opt,name=multicast_ping_slot_period,json=multicastPingSlotPeriod,proto3" json:"multicast_ping_slot_period,omitempty"`
	// Multicast frequency (Hz).
	MulticastFrequency uint32 `protobuf:"varint,6,opt,name=multicast_frequency,json=multicastFrequency,proto3" json:"multicast_frequency,omitempty"`
	// Multicast group ID.
	MulticastGroupId uint32 `protobuf:"varint,7,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	// Multicast timeout.
	// This defines the timeout of the multicast-session.
	// Please refer to the Remote Multicast Setup specification as this field
	// has a different meaning for Class-B and Class-C groups.
	MulticastTimeout uint32 `protobuf:"varint,8,opt,name=multicast_timeout,json=multicastTimeout,proto3" json:"multicast_timeout,omitempty"`
	// Unicast timeout.
	// Set this to the value in which you at least expect an uplink frame from
	// the device. The FUOTA server will wait for the given time before
	// attempting a retry or continuing with the next step.
	UnicastTimeout *duration.Duration `protobuf:"bytes,9,opt,name=unicast_timeout,json=unicastTimeout,proto3" json:"unicast_timeout,omitempty"`
	// Unicast attempt count.
	// The number of attempts before considering an unicast command
	// to be failed.
	UnicastAttemptCount uint32 `protobuf:"varint,10,opt,name=unicast_attempt_count,json=unicastAttemptCount,proto3" json:"unicast_attempt_count,omitempty"`
	// FragmentationFragmentSize.
	// This defines the size of each payload fragment. Please refer to the
	// Regional Parameters specification for the maximum payload sizes
	// per data-rate and region.
	FragmentationFragmentSize uint32 `protobuf:"varint,11,opt,name=fragmentation_fragment_size,json=fragmentationFragmentSize,proto3" json:"fragmentation_fragment_size,omitempty"`
	// Payload.
	Payload []byte `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`
	// Fragmentation redundancy.
	// The number represents the additional redundant frames to send.
	FragmentationRedundancy uint32 `protobuf:"varint,13,opt,name=fragmentation_redundancy,json=fragmentationRedundancy,proto3" json:"fragmentation_redundancy,omitempty"`
	// Fragmentation session index.
	FragmentationSessionIndex uint32 `protobuf:"varint,14,opt,name=fragmentation_session_index,json=fragmentationSessionIndex,proto3" json:"fragmentation_session_index,omitempty"`
	// Fragmentation matrix.
	FragmentationMatrix uint32 `protobuf:"varint,15,opt,name=fragmentation_matrix,json=fragmentationMatrix,proto3" json:"fragmentation_matrix,omitempty"`
	// Block ack delay.
	FragmentationBlockAckDelay uint32 `protobuf:"varint,16,opt,name=fragmentation_block_ack_delay,json=fragmentationBlockAckDelay,proto3" json:"fragmentation_block_ack_delay,omitempty"`
	// Descriptor (4 bytes).
	FragmentationDescriptor []byte   `protobuf:"bytes,17,opt,name=fragmentation_descriptor,json=fragmentationDescriptor,proto3" json:"fragmentation_descriptor,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{0}
}

func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (m *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(m, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *Deployment) GetDevEuis() [][]byte {
	if m != nil {
		return m.DevEuis
	}
	return nil
}

func (m *Deployment) GetMulticastGroupType() MulticastGroupType {
	if m != nil {
		return m.MulticastGroupType
	}
	return MulticastGroupType_CLASS_B
}

func (m *Deployment) GetMulticastDr() uint32 {
	if m != nil {
		return m.MulticastDr
	}
	return 0
}

func (m *Deployment) GetMulticastPingSlotPeriod() uint32 {
	if m != nil {
		return m.MulticastPingSlotPeriod
	}
	return 0
}

func (m *Deployment) GetMulticastFrequency() uint32 {
	if m != nil {
		return m.MulticastFrequency
	}
	return 0
}

func (m *Deployment) GetMulticastGroupId() uint32 {
	if m != nil {
		return m.MulticastGroupId
	}
	return 0
}

func (m *Deployment) GetMulticastTimeout() uint32 {
	if m != nil {
		return m.MulticastTimeout
	}
	return 0
}

func (m *Deployment) GetUnicastTimeout() *duration.Duration {
	if m != nil {
		return m.UnicastTimeout
	}
	return nil
}

func (m *Deployment) GetUnicastAttemptCount() uint32 {
	if m != nil {
		return m.UnicastAttemptCount
	}
	return 0
}

func (m *Deployment) GetFragmentationFragmentSize() uint32 {
	if m != nil {
		return m.FragmentationFragmentSize
	}
	return 0
}

func (m *Deployment) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Deployment) GetFragmentationRedundancy() uint32 {
	if m != nil {
		return m.FragmentationRedundancy
	}
	return 0
}

func (m *Deployment) GetFragmentationSessionIndex() uint32 {
	if m != nil {
		return m.FragmentationSessionIndex
	}
	return 0
}

func (m *Deployment) GetFragmentationMatrix() uint32 {
	if m != nil {
		return m.FragmentationMatrix
	}
	return 0
}

func (m *Deployment) GetFragmentationBlockAckDelay() uint32 {
	if m != nil {
		return m.FragmentationBlockAckDelay
	}
	return 0
}

func (m *Deployment) GetFragmentationDescriptor() []byte {
	if m != nil {
		return m.FragmentationDescriptor
	}
	return nil
}

type CreateDeploymentRequest struct {
	// Deployment.
	Deployment           *Deployment `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateDeploymentRequest) Reset()         { *m = CreateDeploymentRequest{} }
func (m *CreateDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeploymentRequest) ProtoMessage()    {}
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{1}
}

func (m *CreateDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeploymentRequest.Unmarshal(m, b)
}
func (m *CreateDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeploymentRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeploymentRequest.Merge(m, src)
}
func (m *CreateDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeploymentRequest.Size(m)
}
func (m *CreateDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeploymentRequest proto.InternalMessageInfo

func (m *CreateDeploymentRequest) GetDeployment() *Deployment {
	if m != nil {
		return m.Deployment
	}
	return nil
}

type CreateDeploymentResponse struct {
	// ID of the created deployment.
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeploymentResponse) Reset()         { *m = CreateDeploymentResponse{} }
func (m *CreateDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeploymentResponse) ProtoMessage()    {}
func (*CreateDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{2}
}

func (m *CreateDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeploymentResponse.Unmarshal(m, b)
}
func (m *CreateDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeploymentResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeploymentResponse.Merge(m, src)
}
func (m *CreateDeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeploymentResponse.Size(m)
}
func (m *CreateDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeploymentResponse proto.InternalMessageInfo

func (m *CreateDeploymentResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetDeploymentStatusRequest struct {
	// Deployment ID.
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeploymentStatusRequest) Reset()         { *m = GetDeploymentStatusRequest{} }
func (m *GetDeploymentStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeploymentStatusRequest) ProtoMessage()    {}
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{3}
}

func (m *GetDeploymentStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeploymentStatusRequest.Unmarshal(m, b)
}
func (m *GetDeploymentStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeploymentStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetDeploymentStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeploymentStatusRequest.Merge(m, src)
}
func (m *GetDeploymentStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeploymentStatusRequest.Size(m)
}
func (m *GetDeploymentStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeploymentStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeploymentStatusRequest proto.InternalMessageInfo

func (m *GetDeploymentStatusRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeploymentDeviceStatus struct {
	// DevEUI.
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Created at.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at.
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Multicast-group setup completed at.
	McGroupSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=mc_group_setup_completed_at,json=mcGroupSetupCompletedAt,proto3" json:"mc_group_setup_completed_at,omitempty"`
	// Multicast-session completed at.
	McSessionCompletedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=mc_session_completed_at,json=mcSessionCompletedAt,proto3" json:"mc_session_completed_at,omitempty"`
	// Fragmentation session setup completed at.
	FragSessionSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=frag_session_setup_completed_at,json=fragSessionSetupCompletedAt,proto3" json:"frag_session_setup_completed_at,omitempty"`
	// Fragmentation status completed at.
	FragStatusCompletedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=frag_status_completed_at,json=fragStatusCompletedAt,proto3" json:"frag_status_completed_at,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *DeploymentDeviceStatus) Reset()         { *m = DeploymentDeviceStatus{} }
func (m *DeploymentDeviceStatus) String() string { return proto.CompactTextString(m) }
func (*DeploymentDeviceStatus) ProtoMessage()    {}
func (*DeploymentDeviceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{4}
}

func (m *DeploymentDeviceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentDeviceStatus.Unmarshal(m, b)
}
func (m *DeploymentDeviceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentDeviceStatus.Marshal(b, m, deterministic)
}
func (m *DeploymentDeviceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentDeviceStatus.Merge(m, src)
}
func (m *DeploymentDeviceStatus) XXX_Size() int {
	return xxx_messageInfo_DeploymentDeviceStatus.Size(m)
}
func (m *DeploymentDeviceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentDeviceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentDeviceStatus proto.InternalMessageInfo

func (m *DeploymentDeviceStatus) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetMcGroupSetupCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.McGroupSetupCompletedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetMcSessionCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.McSessionCompletedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetFragSessionSetupCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FragSessionSetupCompletedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetFragStatusCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FragStatusCompletedAt
	}
	return nil
}

type GetDeploymentStatusResponse struct {
	// Created at.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at.
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Multicast-group setup completed at.
	McGroupSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=mc_group_setup_completed_at,json=mcGroupSetupCompletedAt,proto3" json:"mc_group_setup_completed_at,omitempty"`
	// Multicast-session completed at.
	McSessionCompletedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=mc_session_completed_at,json=mcSessionCompletedAt,proto3" json:"mc_session_completed_at,omitempty"`
	// Fragmentation session setup completed at.
	FragSessionSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=frag_session_setup_completed_at,json=fragSessionSetupCompletedAt,proto3" json:"frag_session_setup_completed_at,omitempty"`
	// Enqueue completed at.
	EnqueueCompletedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=enqueue_completed_at,json=enqueueCompletedAt,proto3" json:"enqueue_completed_at,omitempty"`
	// Fragmentation status completed at.
	FragStatusCompletedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=frag_status_completed_at,json=fragStatusCompletedAt,proto3" json:"frag_status_completed_at,omitempty"`
	// Per device status.
	DeviceStatus         []*DeploymentDeviceStatus `protobuf:"bytes,8,rep,name=device_status,json=deviceStatus,proto3" json:"device_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetDeploymentStatusResponse) Reset()         { *m = GetDeploymentStatusResponse{} }
func (m *GetDeploymentStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeploymentStatusResponse) ProtoMessage()    {}
func (*GetDeploymentStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{5}
}

func (m *GetDeploymentStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeploymentStatusResponse.Unmarshal(m, b)
}
func (m *GetDeploymentStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeploymentStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetDeploymentStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeploymentStatusResponse.Merge(m, src)
}
func (m *GetDeploymentStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeploymentStatusResponse.Size(m)
}
func (m *GetDeploymentStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeploymentStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeploymentStatusResponse proto.InternalMessageInfo

func (m *GetDeploymentStatusResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetMcGroupSetupCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.McGroupSetupCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetMcSessionCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.McSessionCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetFragSessionSetupCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FragSessionSetupCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetEnqueueCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.EnqueueCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetFragStatusCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FragStatusCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetDeviceStatus() []*DeploymentDeviceStatus {
	if m != nil {
		return m.DeviceStatus
	}
	return nil
}

type GetDeploymentDeviceLogsRequest struct {
	// Deployment ID.
	DeploymentId []byte `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	// DevEUI.
	DevEui               []byte   `protobuf:"bytes,2,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeploymentDeviceLogsRequest) Reset()         { *m = GetDeploymentDeviceLogsRequest{} }
func (m *GetDeploymentDeviceLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeploymentDeviceLogsRequest) ProtoMessage()    {}
func (*GetDeploymentDeviceLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{6}
}

func (m *GetDeploymentDeviceLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeploymentDeviceLogsRequest.Unmarshal(m, b)
}
func (m *GetDeploymentDeviceLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeploymentDeviceLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetDeploymentDeviceLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeploymentDeviceLogsRequest.Merge(m, src)
}
func (m *GetDeploymentDeviceLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeploymentDeviceLogsRequest.Size(m)
}
func (m *GetDeploymentDeviceLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeploymentDeviceLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeploymentDeviceLogsRequest proto.InternalMessageInfo

func (m *GetDeploymentDeviceLogsRequest) GetDeploymentId() []byte {
	if m != nil {
		return m.DeploymentId
	}
	return nil
}

func (m *GetDeploymentDeviceLogsRequest) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

type DeploymentDeviceLog struct {
	// Created at.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// FPort.
	FPort uint32 `protobuf:"varint,2,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// Command.
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// Fields.
	Fields               map[string]string `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeploymentDeviceLog) Reset()         { *m = DeploymentDeviceLog{} }
func (m *DeploymentDeviceLog) String() string { return proto.CompactTextString(m) }
func (*DeploymentDeviceLog) ProtoMessage()    {}
func (*DeploymentDeviceLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{7}
}

func (m *DeploymentDeviceLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentDeviceLog.Unmarshal(m, b)
}
func (m *DeploymentDeviceLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentDeviceLog.Marshal(b, m, deterministic)
}
func (m *DeploymentDeviceLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentDeviceLog.Merge(m, src)
}
func (m *DeploymentDeviceLog) XXX_Size() int {
	return xxx_messageInfo_DeploymentDeviceLog.Size(m)
}
func (m *DeploymentDeviceLog) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentDeviceLog.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentDeviceLog proto.InternalMessageInfo

func (m *DeploymentDeviceLog) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DeploymentDeviceLog) GetFPort() uint32 {
	if m != nil {
		return m.FPort
	}
	return 0
}

func (m *DeploymentDeviceLog) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *DeploymentDeviceLog) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetDeploymentDeviceLogsResponse struct {
	Logs                 []*DeploymentDeviceLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDeploymentDeviceLogsResponse) Reset()         { *m = GetDeploymentDeviceLogsResponse{} }
func (m *GetDeploymentDeviceLogsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeploymentDeviceLogsResponse) ProtoMessage()    {}
func (*GetDeploymentDeviceLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{8}
}

func (m *GetDeploymentDeviceLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeploymentDeviceLogsResponse.Unmarshal(m, b)
}
func (m *GetDeploymentDeviceLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeploymentDeviceLogsResponse.Marshal(b, m, deterministic)
}
func (m *GetDeploymentDeviceLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeploymentDeviceLogsResponse.Merge(m, src)
}
func (m *GetDeploymentDeviceLogsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeploymentDeviceLogsResponse.Size(m)
}
func (m *GetDeploymentDeviceLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeploymentDeviceLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeploymentDeviceLogsResponse proto.InternalMessageInfo

func (m *GetDeploymentDeviceLogsResponse) GetLogs() []*DeploymentDeviceLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
	proto.RegisterEnum("fuota.MulticastGroupType", MulticastGroupType_name, MulticastGroupType_value)
	proto.RegisterType((*Deployment)(nil), "fuota.Deployment")
	proto.RegisterType((*CreateDeploymentRequest)(nil), "fuota.CreateDeploymentRequest")
	proto.RegisterType((*CreateDeploymentResponse)(nil), "fuota.CreateDeploymentResponse")
	proto.RegisterType((*GetDeploymentStatusRequest)(nil), "fuota.GetDeploymentStatusRequest")
	proto.RegisterType((*DeploymentDeviceStatus)(nil), "fuota.DeploymentDeviceStatus")
	proto.RegisterType((*GetDeploymentStatusResponse)(nil), "fuota.GetDeploymentStatusResponse")
	proto.RegisterType((*GetDeploymentDeviceLogsRequest)(nil), "fuota.GetDeploymentDeviceLogsRequest")
	proto.RegisterType((*DeploymentDeviceLog)(nil), "fuota.DeploymentDeviceLog")
	proto.RegisterMapType((map[string]string)(nil), "fuota.DeploymentDeviceLog.FieldsEntry")
	proto.RegisterType((*GetDeploymentDeviceLogsResponse)(nil), "fuota.GetDeploymentDeviceLogsResponse")
}

func init() {
	proto.RegisterFile("fuota/fuota.proto", fileDescriptor_5169117df74b07cc)
}

var fileDescriptor_5169117df74b07cc = []byte{
	// 1114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x5f, 0x6f, 0xdb, 0xb6,
	0x17, 0xad, 0xff, 0x37, 0xd7, 0x4e, 0xea, 0x30, 0xe9, 0xcf, 0x8c, 0x83, 0x26, 0xae, 0x7f, 0x68,
	0x61, 0x74, 0xad, 0x8d, 0xba, 0x2f, 0xcb, 0x06, 0x14, 0x70, 0xe2, 0xa6, 0x0b, 0x96, 0x62, 0xa9,
	0x9c, 0x02, 0xc3, 0x1e, 0xaa, 0x31, 0x22, 0xed, 0x72, 0x91, 0x44, 0x55, 0xa2, 0x8c, 0xba, 0xef,
	0x7b, 0x18, 0xf6, 0x81, 0xf6, 0xe5, 0xf6, 0x30, 0x88, 0xa2, 0x6c, 0x2b, 0xb6, 0x67, 0x6c, 0x5d,
	0x5e, 0x84, 0x90, 0xf7, 0x9c, 0xc3, 0x4b, 0xde, 0xc3, 0xcb, 0x18, 0xb6, 0x87, 0xa1, 0x90, 0xa4,
	0xa3, 0xbe, 0x6d, 0xcf, 0x17, 0x52, 0xa0, 0x82, 0x1a, 0xd4, 0x0f, 0x47, 0x42, 0x8c, 0x6c, 0xd6,
	0x51, 0x93, 0x57, 0xe1, 0xb0, 0x23, 0xb9, 0xc3, 0x02, 0x49, 0x1c, 0x2f, 0xc6, 0xd5, 0x0f, 0x6e,
	0x02, 0x68, 0xe8, 0x13, 0xc9, 0x85, 0x1b, 0xc7, 0x9b, 0xbf, 0x96, 0x00, 0xfa, 0xcc, 0xb3, 0xc5,
	0xc4, 0x61, 0xae, 0x44, 0x8f, 0x60, 0x8b, 0x78, 0x9e, 0xcd, 0x2d, 0x85, 0x31, 0x39, 0xc5, 0x99,
	0x46, 0xa6, 0x95, 0x33, 0x36, 0xe7, 0x66, 0xcf, 0x28, 0xda, 0x83, 0xbb, 0x94, 0x8d, 0x4d, 0x16,
	0xf2, 0x00, 0x67, 0x1b, 0xb9, 0x56, 0xc5, 0x28, 0x51, 0x36, 0x7e, 0x15, 0xf2, 0x00, 0x7d, 0x0f,
	0xbb, 0x4e, 0x68, 0x4b, 0x6e, 0x91, 0x40, 0x9a, 0x23, 0x5f, 0x84, 0x9e, 0x29, 0x27, 0x1e, 0xc3,
	0xb9, 0x46, 0xa6, 0xb5, 0xd5, 0xdd, 0x6b, 0xc7, 0x9b, 0x78, 0x93, 0x40, 0x5e, 0x47, 0x88, 0xcb,
	0x89, 0xc7, 0x0c, 0xe4, 0x2c, 0xcc, 0xa1, 0x87, 0x50, 0x99, 0x89, 0x51, 0x1f, 0xe7, 0x1b, 0x99,
	0xd6, 0xa6, 0x51, 0x9e, 0xce, 0xf5, 0x7d, 0xf4, 0x2d, 0xd4, 0x67, 0x10, 0x8f, 0xbb, 0x23, 0x33,
	0xb0, 0x85, 0x34, 0x3d, 0xe6, 0x73, 0x41, 0x71, 0x41, 0x11, 0x6a, 0x53, 0xc4, 0x05, 0x77, 0x47,
	0x03, 0x5b, 0xc8, 0x0b, 0x15, 0x46, 0x1d, 0xd8, 0x99, 0x91, 0x87, 0x3e, 0xfb, 0x18, 0x32, 0xd7,
	0x9a, 0xe0, 0xa2, 0x62, 0xcd, 0x12, 0x3a, 0x4d, 0x22, 0xe8, 0x29, 0xa0, 0x9b, 0xbb, 0xe3, 0x14,
	0x97, 0x14, 0xbe, 0x9a, 0xde, 0xc0, 0x19, 0x45, 0x5f, 0xc1, 0xf6, 0x0c, 0x1d, 0x55, 0x46, 0x84,
	0x12, 0xdf, 0xbd, 0x01, 0xbe, 0x8c, 0xe7, 0xd1, 0x31, 0xdc, 0x0b, 0xdd, 0x34, 0x74, 0xa3, 0x91,
	0x69, 0x95, 0xbb, 0x7b, 0xed, 0xb8, 0x86, 0xed, 0xa4, 0x86, 0xed, 0xbe, 0xae, 0xa1, 0xb1, 0xa5,
	0x19, 0x89, 0x46, 0x17, 0xee, 0x27, 0x1a, 0x44, 0x4a, 0xe6, 0x78, 0xd2, 0xb4, 0x44, 0xe8, 0x4a,
	0x0c, 0x6a, 0xd1, 0x1d, 0x1d, 0xec, 0xc5, 0xb1, 0x93, 0x28, 0x84, 0x5e, 0xc2, 0xfe, 0xd0, 0x27,
	0xa3, 0xa8, 0xfc, 0x71, 0xd1, 0x93, 0x91, 0x19, 0xf0, 0xcf, 0x0c, 0x97, 0x15, 0x73, 0x2f, 0x05,
	0x39, 0xd5, 0x83, 0x01, 0xff, 0xcc, 0x10, 0x86, 0x92, 0x47, 0x26, 0xb6, 0x20, 0x14, 0x57, 0x1a,
	0x99, 0xc8, 0x0a, 0x7a, 0x88, 0x8e, 0x00, 0xa7, 0x95, 0x7d, 0x46, 0x43, 0x97, 0x92, 0xe8, 0x88,
	0x37, 0xe3, 0xc2, 0xa4, 0xe2, 0xc6, 0x34, 0xbc, 0x98, 0x54, 0xc0, 0x82, 0x40, 0x39, 0xd2, 0xa5,
	0xec, 0x13, 0xde, 0x5a, 0x92, 0xd4, 0x20, 0x46, 0x9c, 0x45, 0x00, 0xf4, 0x1c, 0x76, 0xd3, 0x7c,
	0x87, 0x48, 0x9f, 0x7f, 0xc2, 0xf7, 0xe2, 0x73, 0x48, 0xc5, 0xde, 0xa8, 0x10, 0xea, 0xc1, 0x83,
	0x34, 0xe5, 0xca, 0x16, 0xd6, 0xb5, 0x49, 0xac, 0x6b, 0x93, 0x32, 0x9b, 0x4c, 0x70, 0x55, 0x71,
	0xeb, 0x29, 0xd0, 0x71, 0x84, 0xe9, 0x59, 0xd7, 0xfd, 0x08, 0xb1, 0xb8, 0x61, 0xca, 0x02, 0xcb,
	0xe7, 0x9e, 0x14, 0x3e, 0xde, 0x56, 0x67, 0x93, 0xde, 0x70, 0x7f, 0x1a, 0x6e, 0x9e, 0x43, 0xed,
	0xc4, 0x67, 0x44, 0xb2, 0xd9, 0x65, 0x34, 0x22, 0xd3, 0x05, 0x12, 0x3d, 0x07, 0xa0, 0xd3, 0x49,
	0x75, 0x1f, 0xcb, 0xdd, 0x6d, 0x7d, 0x8f, 0xe6, 0xd0, 0x73, 0xa0, 0xe6, 0x13, 0xc0, 0x8b, 0x6a,
	0x81, 0x27, 0xdc, 0x80, 0xa1, 0x2d, 0xc8, 0xea, 0x6b, 0x5d, 0x31, 0xb2, 0x9c, 0x36, 0x9f, 0x42,
	0xfd, 0x35, 0x93, 0x33, 0xe0, 0x40, 0x12, 0x19, 0x06, 0xc9, 0xe2, 0x37, 0xd1, 0xbf, 0xe7, 0xe1,
	0x7f, 0x33, 0x6c, 0x9f, 0x8d, 0xb9, 0xc5, 0x62, 0x06, 0xaa, 0x41, 0x49, 0x37, 0x05, 0x8d, 0x2f,
	0xc6, 0x3d, 0x01, 0x1d, 0x01, 0x58, 0x2a, 0x1b, 0x6a, 0x12, 0x89, 0xb3, 0x6a, 0x03, 0xf5, 0x05,
	0x53, 0x5f, 0x26, 0x9d, 0xcb, 0xd8, 0xd0, 0xe8, 0x9e, 0x8c, 0xa8, 0xa1, 0x47, 0x13, 0x6a, 0x6e,
	0x3d, 0x55, 0xa3, 0x7b, 0x12, 0xfd, 0x08, 0xfb, 0x8e, 0xa5, 0xef, 0x68, 0xc0, 0x64, 0xe8, 0x99,
	0x96, 0x70, 0x3c, 0x9b, 0x69, 0xad, 0xfc, 0x5a, 0xad, 0x9a, 0x63, 0xa9, 0x8b, 0x3c, 0x88, 0xc8,
	0x27, 0x09, 0xb7, 0x27, 0xd1, 0x5b, 0xa8, 0x39, 0xd6, 0xd4, 0x91, 0x29, 0xd5, 0xc2, 0x5a, 0xd5,
	0x5d, 0xc7, 0xd2, 0x4e, 0x9d, 0x97, 0xfc, 0x19, 0x0e, 0x23, 0x67, 0x4c, 0x45, 0x97, 0x24, 0x5c,
	0x5c, 0x2b, 0xad, 0xae, 0x8c, 0x16, 0x5f, 0x48, 0x7a, 0x10, 0x7b, 0xd3, 0x0c, 0x54, 0xb1, 0xd2,
	0xd2, 0xa5, 0xb5, 0xd2, 0xf7, 0x95, 0xb4, 0xa2, 0xce, 0x89, 0x36, 0x7f, 0x2b, 0xc0, 0xfe, 0x52,
	0xf3, 0x68, 0xaf, 0xa5, 0x2b, 0x9f, 0xf9, 0xf7, 0x95, 0xcf, 0xfe, 0x87, 0x95, 0xcf, 0xdd, 0x4a,
	0xe5, 0xf3, 0xb7, 0x57, 0xf9, 0xc2, 0x97, 0x55, 0xfe, 0x1c, 0x76, 0x99, 0xfb, 0x31, 0x64, 0x21,
	0xfb, 0xa7, 0x86, 0x42, 0x9a, 0x77, 0xdb, 0x3e, 0x42, 0xc7, 0xb0, 0x49, 0x55, 0x2b, 0xd1, 0xb2,
	0xf8, 0x6e, 0x23, 0xd7, 0x2a, 0x77, 0x1f, 0x2c, 0x74, 0xb9, 0xf9, 0x86, 0x63, 0x54, 0xe8, 0xdc,
	0xa8, 0xf9, 0x1e, 0x0e, 0x52, 0x56, 0x8c, 0xa1, 0xe7, 0x62, 0x34, 0xed, 0x65, 0xff, 0x8f, 0x56,
	0x49, 0xc2, 0xe6, 0xb4, 0xad, 0x55, 0x66, 0x93, 0x67, 0x74, 0xbe, 0x8b, 0x65, 0xe7, 0xbb, 0x58,
	0xf3, 0xcf, 0x0c, 0xec, 0x2c, 0x51, 0xff, 0x12, 0x8f, 0xdf, 0x87, 0xe2, 0xd0, 0xf4, 0x84, 0x1f,
	0xfb, 0x7b, 0xd3, 0x28, 0x0c, 0x2f, 0x84, 0x2f, 0xa3, 0x17, 0xd5, 0x12, 0x8e, 0x43, 0x5c, 0xaa,
	0xbc, 0xba, 0x61, 0x24, 0x43, 0xf4, 0x12, 0x8a, 0x43, 0xce, 0x6c, 0x1a, 0xe0, 0xbc, 0x3a, 0xa0,
	0xc7, 0x2b, 0x0e, 0xe8, 0x5c, 0x8c, 0xda, 0xa7, 0x0a, 0xf8, 0xca, 0x95, 0xfe, 0xc4, 0xd0, 0xac,
	0xfa, 0x11, 0x94, 0xe7, 0xa6, 0x51, 0x15, 0x72, 0xd7, 0x6c, 0xa2, 0x72, 0xde, 0x30, 0xa2, 0x3f,
	0xd1, 0x2e, 0x14, 0xc6, 0xc4, 0x0e, 0x99, 0x4a, 0x68, 0xc3, 0x88, 0x07, 0xdf, 0x64, 0xbf, 0xce,
	0x34, 0xdf, 0xc2, 0xe1, 0xca, 0xe3, 0xd5, 0xb7, 0xbd, 0x0d, 0x79, 0x5b, 0x8c, 0x02, 0x9c, 0x51,
	0xb9, 0xd5, 0x57, 0xe7, 0x66, 0x28, 0xdc, 0x93, 0x36, 0xa0, 0xc5, 0xff, 0x03, 0x51, 0x19, 0x4a,
	0x27, 0xe7, 0xbd, 0xc1, 0xc0, 0x3c, 0xae, 0xde, 0x99, 0x0d, 0x4e, 0xaa, 0x99, 0xee, 0x1f, 0x59,
	0x40, 0xa7, 0xef, 0x7e, 0xb8, 0xec, 0x0d, 0x98, 0x3f, 0x66, 0x7e, 0xf4, 0xe5, 0x16, 0x43, 0xef,
	0xa0, 0x7a, 0xf3, 0xb1, 0x43, 0x07, 0x7a, 0xf1, 0x15, 0x6f, 0x6a, 0xfd, 0x70, 0x65, 0x3c, 0xde,
	0x4b, 0xf3, 0x0e, 0x7a, 0x0f, 0x3b, 0x4b, 0x5a, 0x1b, 0x7a, 0xa8, 0x99, 0xab, 0xdf, 0xcc, 0x7a,
	0xf3, 0xef, 0x20, 0x53, 0xfd, 0x5f, 0xa0, 0xb6, 0xe2, 0x40, 0xd1, 0xa3, 0x65, 0x02, 0x0b, 0x7e,
	0xae, 0x3f, 0x5e, 0x07, 0x4b, 0xd6, 0x3a, 0xfe, 0x0e, 0x6a, 0x5c, 0xb4, 0xad, 0x0f, 0xdc, 0xf7,
	0x02, 0x49, 0xac, 0xeb, 0x36, 0xf1, 0x78, 0x4c, 0xfe, 0xe9, 0xd9, 0x88, 0xcb, 0x0f, 0xe1, 0x55,
	0xdb, 0x12, 0x4e, 0xe7, 0xca, 0x17, 0x16, 0x21, 0x7e, 0x67, 0x06, 0x7c, 0x46, 0x3c, 0xde, 0x19,
	0x89, 0xce, 0xf8, 0x45, 0xfc, 0xeb, 0xe3, 0xaa, 0xa8, 0x1c, 0xfd, 0xe2, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x3d, 0x6a, 0x11, 0xe4, 0x93, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FUOTAServerServiceClient is the client API for FUOTAServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FUOTAServerServiceClient interface {
	// CreateDeployment creates the given FUOTA deployment.
	CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*CreateDeploymentResponse, error)
	// GetDeploymentStatus returns the FUOTA deployment status given an ID.
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error)
	// GetDeploymentDeviceLogs returns the FUOTA logs given a deployment ID and DevEUI.
	GetDeploymentDeviceLogs(ctx context.Context, in *GetDeploymentDeviceLogsRequest, opts ...grpc.CallOption) (*GetDeploymentDeviceLogsResponse, error)
}

type fUOTAServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFUOTAServerServiceClient(cc grpc.ClientConnInterface) FUOTAServerServiceClient {
	return &fUOTAServerServiceClient{cc}
}

func (c *fUOTAServerServiceClient) CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*CreateDeploymentResponse, error) {
	out := new(CreateDeploymentResponse)
	err := c.cc.Invoke(ctx, "/fuota.FUOTAServerService/CreateDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTAServerServiceClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error) {
	out := new(GetDeploymentStatusResponse)
	err := c.cc.Invoke(ctx, "/fuota.FUOTAServerService/GetDeploymentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTAServerServiceClient) GetDeploymentDeviceLogs(ctx context.Context, in *GetDeploymentDeviceLogsRequest, opts ...grpc.CallOption) (*GetDeploymentDeviceLogsResponse, error) {
	out := new(GetDeploymentDeviceLogsResponse)
	err := c.cc.Invoke(ctx, "/fuota.FUOTAServerService/GetDeploymentDeviceLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FUOTAServerServiceServer is the server API for FUOTAServerService service.
type FUOTAServerServiceServer interface {
	// CreateDeployment creates the given FUOTA deployment.
	CreateDeployment(context.Context, *CreateDeploymentRequest) (*CreateDeploymentResponse, error)
	// GetDeploymentStatus returns the FUOTA deployment status given an ID.
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error)
	// GetDeploymentDeviceLogs returns the FUOTA logs given a deployment ID and DevEUI.
	GetDeploymentDeviceLogs(context.Context, *GetDeploymentDeviceLogsRequest) (*GetDeploymentDeviceLogsResponse, error)
}

// UnimplementedFUOTAServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFUOTAServerServiceServer struct {
}

func (*UnimplementedFUOTAServerServiceServer) CreateDeployment(ctx context.Context, req *CreateDeploymentRequest) (*CreateDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeployment not implemented")
}
func (*UnimplementedFUOTAServerServiceServer) GetDeploymentStatus(ctx context.Context, req *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentStatus not implemented")
}
func (*UnimplementedFUOTAServerServiceServer) GetDeploymentDeviceLogs(ctx context.Context, req *GetDeploymentDeviceLogsRequest) (*GetDeploymentDeviceLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentDeviceLogs not implemented")
}

func RegisterFUOTAServerServiceServer(s *grpc.Server, srv FUOTAServerServiceServer) {
	s.RegisterService(&_FUOTAServerService_serviceDesc, srv)
}

func _FUOTAServerService_CreateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).CreateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota.FUOTAServerService/CreateDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).CreateDeployment(ctx, req.(*CreateDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTAServerService_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota.FUOTAServerService/GetDeploymentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTAServerService_GetDeploymentDeviceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentDeviceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).GetDeploymentDeviceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota.FUOTAServerService/GetDeploymentDeviceLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).GetDeploymentDeviceLogs(ctx, req.(*GetDeploymentDeviceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FUOTAServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fuota.FUOTAServerService",
	HandlerType: (*FUOTAServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeployment",
			Handler:    _FUOTAServerService_CreateDeployment_Handler,
		},
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _FUOTAServerService_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "GetDeploymentDeviceLogs",
			Handler:    _FUOTAServerService_GetDeploymentDeviceLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fuota/fuota.proto",
}
